config/routes.rb
Rails.application.routes.draw do
  root 'cardwords#index'
  
  resources :cardwords do 
   get :good_response, on: :member
   get :bad_response, on: :member
   get :start_viktorine, on: :collection
  end 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cardword.rb
class Cardword < ApplicationRecord

  def time_to_next_appearance
		if reviewed_at.present?
			-[time_to_next_review.ago-reviewed_at,0].min
		else
			10.years 
		end
	end

  def time_to_next_review
    case group
    when 0
      0.seconds
    when 1
      5.seconds
    when 2
      25.seconds
    when 3
      2.minutes
    when 4
      10.minutes
    when 5
      1.hour
    when 6
      5.hours
    when 7
      1.day
    when 8
      5.days
    when 9
      25.days
    when 10
      4.months
    else
      10.years # если уровень группы вырос до 12 то не когда не будем показывать
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cardwords_controller.rb
class CardwordsController < ApplicationController
  @@test_number = 0 # Счетчик
  @@max_level = 12 # Максимальный уровень в игре
  before_action :find_card , only:%i[ edit create update show good_response bad_response ]

  def destroy
    @cardword = Cardword.find_by id: params[:id]
    @cardword.destroy
    redirect_to cardwords_path
  end 

  def edit 
  end 

  def index
    @cardwords = Cardword.all
  end

  def new
    @cardword = Cardword.new
  end

  def create
    @cardword = Cardword.new  cardword_params
    @cardword.reviewed_at = DateTime.now
    if @cardword.save
      redirect_to cardwords_path
    else
      render :new
    end
  end

  def update 
    if @cardword.update cardword_params
      redirect_to cardwords_path
    else
      render :edit
    end
  end 

  def show 
  end 

  def good_response
    @cardword.increment! :group
    @cardword.reviewed_at = DateTime.now
    if @cardword.group == 11 
      @cardword.hard_word = true
    end 
    @cardword.save
    start_viktorine
  end

  def bad_response 
    @cardword.group = 1
    @cardword.reviewed_at = DateTime.now 
    @cardword.increment! :bad_response
      if  @cardword.bad_response == 10 
        @cardword.hard_word = true 
      end 
    @cardword.save
    start_viktorine
  end

  def start_viktorine               # методы обработки старта викторинры, нарушение всех принципов программировния )
    @cardwords = Cardword.where( group: @@test_number ).last
     if @cardwords.present? and @cardwords.time_to_next_appearance == 0  and @cardwords.hard_word == false
      render :start
     else
      @@test_number = @@test_number + 1
      if @@test_number < @@max_level
        start_viktorine()
      else
        flash[:notice] = "Доступных карточек нет"
        redirect_to root_path
        @@test_number = 0
      end
     end 
  end
  private

  def find_card
    @cardword = Cardword.find_by id: params[:id]
  end 

  def cardword_params
    params.require(:cardword).permit(:word, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible fade show", role: "alert") do
      concat content_tag(:button, '', class: "btn-close", data: { bs_dismiss: 'alert' })
      concat message
      end)
    end
    nil
  end
end

app/helpers/cardwords_helper.rb
module CardwordsHelper
  
end

app/views/cardwords/_form.html.erb
<%= form_with model: @cardword  do |f| %>
<div>
  <%= f.label :Слово  %>
  <%= f.text_field :word, required: true, minlenght: 2, placeholder: "Слово"  %>
</div>
<div>
  <%= f.label :Перевод  %>
  <%= f.text_area :description, required: true, minlenght: 2,placeholder: "Перевод"  %>
</div>
<div>
  <%= f.submit "Создать" %>
</div>
<% end %>

app/views/cardwords/edit.html.erb
<h1> Edit cardword </h1>

<%= render 'form'%>

app/views/cardwords/index.html.erb
<div class="d-grid gap-2 col-6 mx-auto">
 <%= link_to 'Старт',start_viktorine_cardwords_path ,class: "btn btn-success" %>
</div>
<!--<div class="container">
<% @cardwords.each do |cardword| %>
  <h2><%= cardword.word %>
  <h2><%= cardword.description %>
  <h2><%= cardword.response %>
  <h2><%= cardword.group %>
  <h2><%= cardword.incorrect_group %>
  <h2><%= cardword.date_change_group%>
  <h2><%= cardword.hard_word %> -->
 
  
  <!-- <%= link_to 'Show', cardword_path(cardword),class: "btn btn-primary" %>
  <%= link_to 'Edit', edit_cardword_path(cardword),class: "btn btn-primary" %>
  <%= button_to 'Destroy', cardword_path(cardword),class: "btn btn-primary" ,method: :delete %>
<% end %>
</div>--!>

app/views/cardwords/new.html.erb
<h1>Новая карточка </h1>

<%= render 'form'%>

app/views/cardwords/show.html.erb
<div class="container-sm">

<div class="card text-center">
  <div class="card-header">
    Карточки
  </div>
  <div class="card-body">
    <h5 class="card-title">
        <%= @cardword.word%> 
    </h5>
<div class="accordion accordion-flush" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
    
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
       Перевод
       
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        <li>Id: <%= @cardword.id%></li>
       <li>Перевод: <%= @cardword.description%></li>
       <li>Правильные ответы: <%= @cardword.response %></li>
       <li>Уровень сложности: <%= @cardword.group %></li>
       <td> время до след показа <%= @cardword.time_to_next_appearance  %>
       <li>Время: <%= @cardword.date_change_group%></li>
       <li>Сложное слово: <%= @cardword.hard_word %></li>
       <li>Неверные ответы:<%= @cardword.bad_response %></li>
       <li>Время :<%= @cardword.reviewed_at %></li>
        <p>
        <%= link_to 'Верно',good_response_cardword_path ,class: "btn btn-success" %>
        <%= link_to 'Не верно',bad_response_cardword_path ,class: "btn btn-danger" %>
        </p>
        </div>
    </div>
  </div>
</div>
  </div>
  <div class="card-footer text-muted">
    время 
  </div>
</div>
</div>

app/views/cardwords/start.html.erb
<div class="container-sm">

<div class="card text-center">
  <div class="card-header">
    Карточки
  </div>
  <div class="card-body">
    <h5 class="card-title">
        <%= @cardwords.word%> 
    </h5>
<div class="accordion accordion-flush" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
    
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
       Перевод
       
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
      <div class="accordion-body">
        <li>Id: <%= @cardwords.id%></li>
       <li>Перевод: <%= @cardwords.description%></li>
       <li>Правильные ответы: <%= @cardwords.response %></li>
       <li>Уровень сложности: <%= @cardwords.group %></li>
       <li>Время: <%= @cardwords.date_change_group%></li>
       <li>Сложное слово: <%= @cardwords.hard_word %></li>
       <li>Неверные ответы:<%= @cardwords.bad_response %></li>
        <p>
         <%= link_to 'Верно',good_response_cardword_path(@cardwords) ,class: "btn btn-success" %>
         <%= link_to 'Не верно',bad_response_cardword_path(@cardwords) ,class: "btn btn-danger" %>
        </p>
        </div>
    </div>
  </div>
</div>



  </div>
  <div class="card-footer text-muted">
    время 
  </div>
</div>
</div>
  

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Главная', root_path, class: "navbar-brand"  %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        
        <li class="nav-item">
             <%= link_to 'Новая карточка', new_cardword_path, class: "nav-link"  %>
        </li>
        <%# <li class="nav-item">
          <a class="nav-link" href="root_path">Home</a>
        </li> %>
        <%# <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> %>
      </ul>
    </div>
  </div>
</nav>

      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Word</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
<div class="container">
  <!-- Content here -->

  <body>
    <%= render 'layouts/nav'%>
    <nav>
      
       <%# <%= link_to 'new', new_cardword_path, class: "btn btn-primary"  %> 
       <%# <%=  link_to 'Home', root_path, class: "btn btn-primary" %>
       <%# <%=  link_to 'CardWord', cardwords_path, class: "btn btn-primary" %> 
      
    </nav>
    <main>
  <%= flash_messages %>
  <%= yield %>
  </main>
  </body>
</html>

</div>